import AllEvent from "./_Component/AllEvent";

export const metadata = {
  title: "Event",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <AllEvent />
    </div>
  );
}
